import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';

type QuizQuestion = {
  question: string;
  options: string[];
  correct_index: number;
  explanation: string;
};

type QuizProps = {
  topic: string;
  context?: string;
};

export default function Quiz({ topic, context = '' }: QuizProps) {
  const [loading, setLoading] = useState(false);
  const [started, setStarted] = useState(false);
  const [quizData, setQuizData] = useState<QuizQuestion[]>([]);
  const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0);
  const [selectedOption, setSelectedOption] = useState<number | null>(null);
  const [score, setScore] = useState(0);
  const [quizFinished, setQuizFinished] = useState(false);
  const [showFeedback, setShowFeedback] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchQuiz = async () => {
    setLoading(true);
    setError(null);

    try {
      const response = await fetch('https://physical-ai-textbook.onrender.com/quiz', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ topic, context }),
      });

      if (!response.ok) {
        throw new Error('Failed to generate quiz');
      }

      const data = await response.json();
      setQuizData(data.quiz);
      setStarted(true);
    } catch (err) {
      console.error(err);
      setError('CONNECTION_FAILED // Unable to generate quiz. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleOptionSelect = (index: number) => {
    if (showFeedback) return; // Prevent changing answer after submission

    setSelectedOption(index);
    setShowFeedback(true);

    if (index === quizData[currentQuestionIndex].correct_index) {
      setScore((prev) => prev + 1);
    }
  };

  const handleNextQuestion = () => {
    if (currentQuestionIndex < quizData.length - 1) {
      setCurrentQuestionIndex((prev) => prev + 1);
      setSelectedOption(null);
      setShowFeedback(false);
    } else {
      setQuizFinished(true);
    }
  };

  const handleRestart = () => {
    setStarted(false);
    setQuizData([]);
    setCurrentQuestionIndex(0);
    setSelectedOption(null);
    setScore(0);
    setQuizFinished(false);
    setShowFeedback(false);
    setError(null);
  };

  const currentQuestion = quizData[currentQuestionIndex];

  const containerVariants = {
    hidden: { opacity: 0, scale: 0.95 },
    visible: {
      opacity: 1,
      scale: 1,
      transition: { type: 'spring' as const, stiffness: 300, damping: 25 },
    },
    exit: { opacity: 0, scale: 0.95, transition: { duration: 0.2 } },
  };

  const optionVariants = {
    hidden: { opacity: 0, x: -20 },
    visible: (i: number) => ({
      opacity: 1,
      x: 0,
      transition: { delay: i * 0.1, type: 'spring' as const, stiffness: 300, damping: 25 },
    }),
  };

  return (
    <div className="quiz-container">
      {/* HUD Corner Decorations */}
      <div className="quiz-corner quiz-corner-tl"></div>
      <div className="quiz-corner quiz-corner-tr"></div>
      <div className="quiz-corner quiz-corner-bl"></div>
      <div className="quiz-corner quiz-corner-br"></div>

      {/* Scanline Effect */}
      <div className="quiz-scanline"></div>

      <AnimatePresence mode="wait">
        {/* Start Screen */}
        {!started && !loading && (
          <motion.div
            key="start"
            className="quiz-start-screen"
            variants={containerVariants}
            initial="hidden"
            animate="visible"
            exit="exit"
          >
            <div className="quiz-header">
              <span className="quiz-status-dot"></span>
              <span className="quiz-title">KNOWLEDGE_ASSESSMENT</span>
            </div>

            <div className="quiz-topic-display">
              <span className="quiz-label">// TOPIC:</span>
              <h2 className="quiz-topic-name">{topic}</h2>
            </div>

            <p className="quiz-description">
              Test your understanding with a 3-question adaptive assessment generated by AI.
            </p>

            {error && (
              <div className="quiz-error">
                <span>⚠ {error}</span>
              </div>
            )}

            <button className="quiz-start-btn" onClick={fetchQuiz}>
              <span className="btn-text">START ASSESSMENT</span>
              <span className="btn-arrow">→</span>
            </button>
          </motion.div>
        )}

        {/* Loading Screen */}
        {loading && (
          <motion.div
            key="loading"
            className="quiz-loading"
            variants={containerVariants}
            initial="hidden"
            animate="visible"
            exit="exit"
          >
            <div className="quiz-loader"></div>
            <p className="quiz-loading-text">
              GENERATING_ASSESSMENT<span className="loading-dots"></span>
            </p>
          </motion.div>
        )}

        {/* Question View */}
        {started && !quizFinished && currentQuestion && (
          <motion.div
            key={`question-${currentQuestionIndex}`}
            className="quiz-question-view"
            variants={containerVariants}
            initial="hidden"
            animate="visible"
            exit="exit"
          >
            {/* Progress Header */}
            <div className="quiz-progress-header">
              <div className="quiz-progress-info">
                <span className="quiz-status-dot"></span>
                <span className="quiz-progress-label">
                  QUESTION {currentQuestionIndex + 1}/{quizData.length}
                </span>
              </div>
              <div className="quiz-score-display">
                <span className="quiz-score-label">SCORE:</span>
                <span className="quiz-score-value">{score}</span>
              </div>
            </div>

            {/* Progress Bar */}
            <div className="quiz-progress-bar">
              <div
                className="quiz-progress-fill"
                style={{ width: `${((currentQuestionIndex + 1) / quizData.length) * 100}%` }}
              ></div>
            </div>

            {/* Question */}
            <div className="quiz-question-container">
              <p className="quiz-question-text">{currentQuestion.question}</p>
            </div>

            {/* Options */}
            <div className="quiz-options">
              {currentQuestion.options.map((option, index) => {
                const isSelected = selectedOption === index;
                const isCorrect = index === currentQuestion.correct_index;
                const showCorrect = showFeedback && isCorrect;
                const showWrong = showFeedback && isSelected && !isCorrect;

                return (
                  <motion.button
                    key={index}
                    className={`quiz-option ${isSelected ? 'selected' : ''} ${showCorrect ? 'correct' : ''} ${showWrong ? 'wrong' : ''}`}
                    onClick={() => handleOptionSelect(index)}
                    custom={index}
                    variants={optionVariants}
                    initial="hidden"
                    animate="visible"
                    disabled={showFeedback}
                  >
                    <span className="option-letter">{String.fromCharCode(65 + index)}</span>
                    <span className="option-text">{option}</span>
                    {showCorrect && <span className="option-icon">✓</span>}
                    {showWrong && <span className="option-icon">✗</span>}
                  </motion.button>
                );
              })}
            </div>

            {/* Feedback */}
            <AnimatePresence>
              {showFeedback && (
                <motion.div
                  className={`quiz-feedback ${selectedOption === currentQuestion.correct_index ? 'correct' : 'wrong'}`}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -10 }}
                >
                  <div className="feedback-header">
                    {selectedOption === currentQuestion.correct_index ? (
                      <span className="feedback-result correct">✓ CORRECT</span>
                    ) : (
                      <span className="feedback-result wrong">✗ INCORRECT</span>
                    )}
                  </div>
                  <p className="feedback-explanation">{currentQuestion.explanation}</p>
                </motion.div>
              )}
            </AnimatePresence>

            {/* Next Button */}
            {showFeedback && (
              <motion.button
                className="quiz-next-btn"
                onClick={handleNextQuestion}
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 0.3 }}
              >
                {currentQuestionIndex < quizData.length - 1 ? 'NEXT QUESTION →' : 'VIEW RESULTS →'}
              </motion.button>
            )}
          </motion.div>
        )}

        {/* Results Screen */}
        {quizFinished && (
          <motion.div
            key="results"
            className="quiz-results"
            variants={containerVariants}
            initial="hidden"
            animate="visible"
            exit="exit"
          >
            <div className="quiz-header">
              <span className="quiz-status-dot"></span>
              <span className="quiz-title">ASSESSMENT_COMPLETE</span>
            </div>

            <div className="quiz-final-score">
              <span className="score-label">FINAL SCORE</span>
              <div className="score-display">
                <span className="score-value">{score}</span>
                <span className="score-divider">/</span>
                <span className="score-total">{quizData.length}</span>
              </div>
              <div className="score-percentage">
                {Math.round((score / quizData.length) * 100)}% ACCURACY
              </div>
            </div>

            <div className="quiz-grade">
              {score === quizData.length && (
                <span className="grade excellent">EXCELLENT // Perfect Score!</span>
              )}
              {score === quizData.length - 1 && (
                <span className="grade good">GOOD // Almost there!</span>
              )}
              {score < quizData.length - 1 && score > 0 && (
                <span className="grade review">REVIEW_RECOMMENDED // Keep learning!</span>
              )}
              {score === 0 && (
                <span className="grade retry">RETRY_SUGGESTED // Don't give up!</span>
              )}
            </div>

            <button className="quiz-restart-btn" onClick={handleRestart}>
              <span className="btn-text">RESTART ASSESSMENT</span>
              <span className="btn-icon">↻</span>
            </button>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Styles */}
      <style>{`
        .quiz-container {
          background: rgba(5, 5, 5, 0.98);
          border: 1px solid #00f3ff;
          border-radius: 8px;
          padding: 24px;
          position: relative;
          overflow: hidden;
          font-family: 'Rajdhani', sans-serif;
          box-shadow: 0 0 20px rgba(0, 243, 255, 0.1);
          min-height: 400px;
          display: flex;
          flex-direction: column;
        }

        /* HUD Corners */
        .quiz-corner {
          position: absolute;
          width: 20px;
          height: 20px;
          border-color: #00f3ff;
          border-style: solid;
          z-index: 10;
          pointer-events: none;
        }
        .quiz-corner-tl { top: 4px; left: 4px; border-width: 2px 0 0 2px; }
        .quiz-corner-tr { top: 4px; right: 4px; border-width: 2px 2px 0 0; }
        .quiz-corner-bl { bottom: 4px; left: 4px; border-width: 0 0 2px 2px; }
        .quiz-corner-br { bottom: 4px; right: 4px; border-width: 0 2px 2px 0; }

        /* Scanline */
        .quiz-scanline {
          position: absolute;
          top: 0;
          left: 0;
          right: 0;
          height: 2px;
          background: linear-gradient(90deg, transparent, rgba(0, 243, 255, 0.5), transparent);
          animation: quizScan 3s linear infinite;
          pointer-events: none;
          z-index: 5;
        }
        @keyframes quizScan {
          0% { top: 0; opacity: 0; }
          10% { opacity: 1; }
          90% { opacity: 1; }
          100% { top: 100%; opacity: 0; }
        }

        /* Header */
        .quiz-header {
          display: flex;
          align-items: center;
          gap: 10px;
          margin-bottom: 20px;
        }
        .quiz-status-dot {
          width: 8px;
          height: 8px;
          background: #00ff88;
          border-radius: 50%;
          box-shadow: 0 0 8px #00ff88;
          animation: statusBlink 1.5s infinite;
        }
        @keyframes statusBlink {
          0%, 100% { opacity: 1; }
          50% { opacity: 0.6; }
        }
        .quiz-title {
          font-family: 'Orbitron', sans-serif;
          font-size: 12px;
          color: #00f3ff;
          letter-spacing: 2px;
          font-weight: bold;
        }

        /* Start Screen */
        .quiz-start-screen {
          flex: 1;
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          text-align: center;
        }
        .quiz-topic-display {
          margin: 20px 0;
        }
        .quiz-label {
          font-family: 'JetBrains Mono', monospace;
          font-size: 11px;
          color: #00f3ff;
          opacity: 0.7;
        }
        .quiz-topic-name {
          font-family: 'Orbitron', sans-serif;
          font-size: 24px;
          color: #e0e0e0;
          margin: 8px 0 0 0;
          text-transform: uppercase;
          letter-spacing: 2px;
        }
        .quiz-description {
          color: #808080;
          font-size: 14px;
          max-width: 300px;
          line-height: 1.6;
          margin-bottom: 30px;
        }
        .quiz-error {
          background: rgba(255, 68, 68, 0.1);
          border: 1px solid #ff4444;
          border-radius: 4px;
          padding: 12px 16px;
          margin-bottom: 20px;
          color: #ff4444;
          font-family: 'JetBrains Mono', monospace;
          font-size: 12px;
        }
        .quiz-start-btn {
          background: rgba(0, 243, 255, 0.1);
          border: 2px solid #00f3ff;
          color: #00f3ff;
          padding: 14px 32px;
          font-family: 'Orbitron', sans-serif;
          font-size: 14px;
          font-weight: bold;
          cursor: pointer;
          border-radius: 4px;
          display: flex;
          align-items: center;
          gap: 12px;
          transition: all 0.3s ease;
          text-transform: uppercase;
          letter-spacing: 2px;
        }
        .quiz-start-btn:hover {
          background: #00f3ff;
          color: #050505;
          box-shadow: 0 0 30px rgba(0, 243, 255, 0.5);
        }
        .btn-arrow {
          transition: transform 0.3s ease;
        }
        .quiz-start-btn:hover .btn-arrow {
          transform: translateX(4px);
        }

        /* Loading */
        .quiz-loading {
          flex: 1;
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
        }
        .quiz-loader {
          width: 50px;
          height: 50px;
          border: 3px solid rgba(0, 243, 255, 0.2);
          border-top-color: #00f3ff;
          border-radius: 50%;
          animation: spin 1s linear infinite;
        }
        @keyframes spin {
          to { transform: rotate(360deg); }
        }
        .quiz-loading-text {
          margin-top: 20px;
          color: #00f3ff;
          font-family: 'JetBrains Mono', monospace;
          font-size: 12px;
          animation: pulse 1s infinite;
        }
        @keyframes pulse {
          0%, 100% { opacity: 1; }
          50% { opacity: 0.5; }
        }
        .loading-dots::after {
          content: '';
          animation: dots 1.5s infinite;
        }
        @keyframes dots {
          0% { content: ''; }
          25% { content: '.'; }
          50% { content: '..'; }
          75% { content: '...'; }
        }

        /* Question View */
        .quiz-question-view {
          flex: 1;
          display: flex;
          flex-direction: column;
        }
        .quiz-progress-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 16px;
        }
        .quiz-progress-info {
          display: flex;
          align-items: center;
          gap: 10px;
        }
        .quiz-progress-label {
          font-family: 'Orbitron', sans-serif;
          font-size: 11px;
          color: #00f3ff;
          letter-spacing: 1px;
        }
        .quiz-score-display {
          display: flex;
          align-items: center;
          gap: 8px;
          font-family: 'JetBrains Mono', monospace;
        }
        .quiz-score-label {
          font-size: 10px;
          color: #808080;
        }
        .quiz-score-value {
          font-size: 16px;
          color: #00ff88;
          font-weight: bold;
        }

        /* Progress Bar */
        .quiz-progress-bar {
          height: 3px;
          background: rgba(0, 243, 255, 0.2);
          border-radius: 2px;
          margin-bottom: 24px;
          overflow: hidden;
        }
        .quiz-progress-fill {
          height: 100%;
          background: linear-gradient(90deg, #00f3ff, #00ff88);
          transition: width 0.3s ease;
          box-shadow: 0 0 10px rgba(0, 243, 255, 0.5);
        }

        /* Question */
        .quiz-question-container {
          background: rgba(0, 243, 255, 0.05);
          border: 1px solid rgba(0, 243, 255, 0.2);
          border-left: 3px solid #00f3ff;
          border-radius: 4px;
          padding: 20px;
          margin-bottom: 20px;
        }
        .quiz-question-text {
          color: #e0e0e0;
          font-size: 16px;
          line-height: 1.6;
          margin: 0;
        }

        /* Options */
        .quiz-options {
          display: flex;
          flex-direction: column;
          gap: 12px;
          margin-bottom: 20px;
        }
        .quiz-option {
          display: flex;
          align-items: center;
          gap: 14px;
          background: rgba(255, 255, 255, 0.02);
          border: 1px solid rgba(255, 255, 255, 0.1);
          border-radius: 4px;
          padding: 14px 16px;
          cursor: pointer;
          transition: all 0.2s ease;
          text-align: left;
        }
        .quiz-option:hover:not(:disabled) {
          background: rgba(0, 243, 255, 0.05);
          border-color: rgba(0, 243, 255, 0.3);
        }
        .quiz-option.selected {
          background: rgba(0, 243, 255, 0.1);
          border-color: #00f3ff;
        }
        .quiz-option.correct {
          background: rgba(0, 255, 136, 0.1);
          border-color: #00ff88;
        }
        .quiz-option.wrong {
          background: rgba(255, 68, 68, 0.1);
          border-color: #ff4444;
        }
        .quiz-option:disabled {
          cursor: not-allowed;
        }
        .option-letter {
          width: 28px;
          height: 28px;
          display: flex;
          align-items: center;
          justify-content: center;
          background: rgba(0, 243, 255, 0.1);
          border: 1px solid rgba(0, 243, 255, 0.3);
          border-radius: 4px;
          font-family: 'Orbitron', sans-serif;
          font-size: 12px;
          color: #00f3ff;
          font-weight: bold;
          flex-shrink: 0;
        }
        .quiz-option.correct .option-letter {
          background: rgba(0, 255, 136, 0.2);
          border-color: #00ff88;
          color: #00ff88;
        }
        .quiz-option.wrong .option-letter {
          background: rgba(255, 68, 68, 0.2);
          border-color: #ff4444;
          color: #ff4444;
        }
        .option-text {
          flex: 1;
          color: #e0e0e0;
          font-size: 14px;
        }
        .option-icon {
          font-size: 18px;
          font-weight: bold;
        }
        .quiz-option.correct .option-icon {
          color: #00ff88;
        }
        .quiz-option.wrong .option-icon {
          color: #ff4444;
        }

        /* Feedback */
        .quiz-feedback {
          background: rgba(255, 255, 255, 0.02);
          border-radius: 4px;
          padding: 16px;
          margin-bottom: 16px;
        }
        .quiz-feedback.correct {
          border: 1px solid rgba(0, 255, 136, 0.3);
          border-left: 3px solid #00ff88;
        }
        .quiz-feedback.wrong {
          border: 1px solid rgba(255, 68, 68, 0.3);
          border-left: 3px solid #ff4444;
        }
        .feedback-header {
          margin-bottom: 8px;
        }
        .feedback-result {
          font-family: 'Orbitron', sans-serif;
          font-size: 12px;
          font-weight: bold;
          letter-spacing: 1px;
        }
        .feedback-result.correct {
          color: #00ff88;
        }
        .feedback-result.wrong {
          color: #ff4444;
        }
        .feedback-explanation {
          color: #a0a0a0;
          font-size: 13px;
          line-height: 1.6;
          margin: 0;
        }

        /* Next Button */
        .quiz-next-btn {
          align-self: flex-end;
          background: rgba(0, 243, 255, 0.1);
          border: 1px solid #00f3ff;
          color: #00f3ff;
          padding: 12px 24px;
          font-family: 'Orbitron', sans-serif;
          font-size: 11px;
          font-weight: bold;
          cursor: pointer;
          border-radius: 4px;
          transition: all 0.3s ease;
          letter-spacing: 1px;
        }
        .quiz-next-btn:hover {
          background: #00f3ff;
          color: #050505;
          box-shadow: 0 0 20px rgba(0, 243, 255, 0.4);
        }

        /* Results */
        .quiz-results {
          flex: 1;
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          text-align: center;
        }
        .quiz-final-score {
          margin: 30px 0;
        }
        .score-label {
          font-family: 'JetBrains Mono', monospace;
          font-size: 11px;
          color: #808080;
          letter-spacing: 2px;
        }
        .score-display {
          display: flex;
          align-items: baseline;
          justify-content: center;
          gap: 8px;
          margin: 12px 0;
        }
        .score-value {
          font-family: 'Orbitron', sans-serif;
          font-size: 64px;
          color: #00ff88;
          font-weight: bold;
          text-shadow: 0 0 30px rgba(0, 255, 136, 0.5);
        }
        .score-divider {
          font-size: 32px;
          color: #404040;
        }
        .score-total {
          font-family: 'Orbitron', sans-serif;
          font-size: 32px;
          color: #808080;
        }
        .score-percentage {
          font-family: 'JetBrains Mono', monospace;
          font-size: 14px;
          color: #00f3ff;
          letter-spacing: 1px;
        }

        /* Grade */
        .quiz-grade {
          margin-bottom: 30px;
        }
        .grade {
          font-family: 'JetBrains Mono', monospace;
          font-size: 12px;
          padding: 8px 16px;
          border-radius: 4px;
        }
        .grade.excellent {
          background: rgba(0, 255, 136, 0.1);
          border: 1px solid #00ff88;
          color: #00ff88;
        }
        .grade.good {
          background: rgba(0, 243, 255, 0.1);
          border: 1px solid #00f3ff;
          color: #00f3ff;
        }
        .grade.review {
          background: rgba(255, 200, 0, 0.1);
          border: 1px solid #ffc800;
          color: #ffc800;
        }
        .grade.retry {
          background: rgba(255, 68, 68, 0.1);
          border: 1px solid #ff4444;
          color: #ff4444;
        }

        /* Restart Button */
        .quiz-restart-btn {
          background: rgba(0, 243, 255, 0.1);
          border: 2px solid #00f3ff;
          color: #00f3ff;
          padding: 14px 28px;
          font-family: 'Orbitron', sans-serif;
          font-size: 12px;
          font-weight: bold;
          cursor: pointer;
          border-radius: 4px;
          display: flex;
          align-items: center;
          gap: 10px;
          transition: all 0.3s ease;
          letter-spacing: 1px;
        }
        .quiz-restart-btn:hover {
          background: #00f3ff;
          color: #050505;
          box-shadow: 0 0 30px rgba(0, 243, 255, 0.5);
        }
        .btn-icon {
          font-size: 16px;
          transition: transform 0.3s ease;
        }
        .quiz-restart-btn:hover .btn-icon {
          transform: rotate(360deg);
        }
      `}</style>
    </div>
  );
}
